image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Flutter
    init: |
      git clone https://github.com/flutter/flutter.git -b stable
      export PATH="$PATH:/workspace/flutter/bin"
      flutter doctor

vscode:
  extensions:
    - dart-code.flutter
    - dart-code.dart-code

ports:
  - port: 3000
    onOpen: open-preview
